name: Демо использования секрета в CI/CD
on: [push]
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - if: ${{ secrets.SECRET == 'secret-word' }}
        name: Check if secret is correct
        run: echo "true"
